image: openjdk:8
vscode:
  extensions:
    - scala-lang.scala@0.3.9:kklqw+c/dNRmtTU8B5repw==
    - scalameta.metals@1.7.8:oixMSF1r3cXQPfOQ34+sTA==
tasks:
- before: export PATH=$PATH:/usr/local/openjdk-8/bin
- init: >
    curl -L https://github.com/scalacenter/bloop/releases/download/v1.4.0-RC1/install.py | python &&
    echo "alias bloop=~/.bloop/bloop" >> ~/.bashrc &&
    curl -L https://piccolo.link/sbt-1.3.8.tgz > ~/sbt.tar.gz &&
    tar -C ~ -xvf ~/sbt.tar.gz &&
    ~/sbt/bin/sbt -Dbloop.export-jar-classifiers=sources bloopInstall
- command: >
    source ~/.bloop/bash/bloop &&
    alias bloop=~/.bloop/bloop &&
    alias sbt=~/sbt/bin/sbt &&
    ~/.bloop/bloop server &>/dev/null &
